### ISSUE TITLE
very useful gem, works no longer with rails 4.0.8

### ISSUE THREAD

**Issue by fyyyyy** [mrsweaters/mithril-rails#3]
thanks for this gem i find it very useful for rails/mithril

However since merging the branch i get an JS error "undefined is not a function". The compilation seems broken.

We changed the rails dependency that seems to cause the issue with recent updates, any idea why ?
-  s.add_dependency "rails", "~> 4.1.0"
-  s.add_dependency "rails", "~> 4.0.8"

Thanks
